### ISSUE TITLE
Automate the Essential Genes solr core production and deployment

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#425] opened 2020-08-24 14:09 UTC
Need to ensure that the Essential Genes and Orthologs cores are generated periodically and deployed to the production servers.

**Comment by mrelac-ebi** [comment] 2020-10-29 08:07
I'm closing this as it's a duplicate of #425, which has been completed.

**Closed** 2021-03-05 15:19 UTC
