### ISSUE TITLE
Mismatched images  for ECG parameter

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#603] opened 2021-05-26 09:55 UTC
Images on image comparator and thumbnail are showing an Xray image, for an ECG parameter.  Should be a trace file

https://www.mousephenotype.org/data/imageComparator?&parameter_stable_id=IMPC_ECG_025_001&acc=MGI:3040687

@kbab thinks this might be a disconnect in the way we are interpreting image_associations

To reproduce:
1) Navigate to https://www.mousephenotype.org/data/genes/MGI:3040687
2) Scroll down to the Associated Images section
3) Observe the headline image is an Xray instead of a waveform
4) Click on the "Xray" image
5) It will navigate to https://www.mousephenotype.org/data/imageComparator?&parameter_stable_id=IMPC_ECG_025_001&acc=MGI:3040687

Expected behavior:
* The images should be ECG images

Actual behavior:
* The images are Xray images
![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/03da36fb-4528-4a11-b01d-a1718338fa64)

**Comment by kbab** [comment] 2021-05-26 10:18
The issue is that the base path for pdfs (loaded as annotations in omero) should be treated differently from images. It should be https://www.ebi.ac.uk/mi/media/omero/webclient/annotation/ followed by the omero ID. E.g. https://www.ebi.ac.uk/mi/media/omero/webclient/annotation/64646 as opposed to https://www.ebi.ac.uk/mi/media/omero/webgateway/render_image/64646

We need to fix this and regenerate the impc_images core. I have communicated this to @ficolo and between the both of us we will resolve the issue

**Comment by ficolo** [comment] 2021-05-26 10:37
I recommend you to do this on the frontend. As I did for the issue reported by Sharon on January:


https://github.com/mpi2/PhenotypeData/blob/0ee8e7e0b8035ffcdd7775c3aa04ad1fc8c0b214/data-model-solr/src/main/java/org/mousephenotype/cda/solr/service/ImageService.java#L640

**Comment by ficolo** [comment] 2021-05-26 10:44
As you can see there this works fine for all the records that have a file_type="application/pdf" the issue Jeremy is reporting has to do with 80 entries for ECG images that don't have any file_type. You could change that code to fallback on checking the extension ".pdf" on the field "download_file_path" when there is not a file_type fields.

**Comment by kbab** [comment] 2021-06-03 13:59
Followed @ficolo suggestion and added condition to use file extension. Fixes issue on my local version - code committed to master branch.

**Closed** 2021-06-18 10:34 UTC
Labels: bug, images
