### ISSUE TITLE
Infertility rows looks different on the Gene Page/Significant Phenotype table 

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#542] opened 2021-02-04 12:08 UTC
![Screenshot 2021-02-04 at 12.04.13.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/0a81dfe3-0b87-47c6-9c37-bc5bd97a98eb)

**Comment by jmason-ebi** [comment] 2021-04-19 15:30
Why is there a screenshot if Impress here? lol

**Comment by jmason-ebi** [comment] 2021-04-19 15:33
Is this a duplicate of #520 ?

**Comment by ficolo** [comment] 2021-11-08 14:13
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565323731626232653333633565366234363961393130662f33656262656366612d343737662d346134372d613839392d313430626638353832656539.png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/79c13742-0022-4b45-ba74-a35864ec31a5)

**Closed** 2021-11-18 14:11 UTC
Labels: bug
