### ISSUE TITLE
3i images missing from the website

### ISSUE THREAD

**Issue by rwilson-ebi** [mpi2/PhenotypeData#642] opened 2021-09-14 16:12 UTC
The 3i images are missing from the website. This is probably due to a step in the ETL process that does not identify these images correctly from the data included in the experiment core because the 3i images use a different nomenclature and format from other images

We need to identify the 3i images and update the ETL process to include them on the website 

(Omero IDs in the impc_images core? - please update with more information)

**Comment by kbab** [comment] 2021-09-21 09:52
Omero IDs are present in the impc_images core. The bug arose because their associated xml files were not generated by the DCC and the download_file_path is not the IMPC standard one.

One way of resolving the issue is to add " OR 'images/3i' " to the query that selects items during the ETL. 

Below is the filter query from the old OmeroUpload script showing the inclusion of the ' OR ' in the query condition:

solrFilterQuery = """experiment/select?q=observation_type:image_record&fq=(download_file_path:(*mousephenotype.org*%20OR%20*images/3i*)%20AND%20-download_file_path:*.mov%20AND%20-download_file_path:*.fcs%20AND%20-download_file_path:*.bz2%20AND%20-download_file_path:*.nrrd)&rows=10000000&wt=json&fl=download_file_path,pipeline_stable_id,procedure_stable_id,parameter_stable_id,production_center,phenotyping_center"""

**Closed** 2022-02-14 13:30 UTC
Labels: bug
